- updated to 2.6.0
Changed files:
    amanda-bashizm.patch -> 1.2
    amanda-chg-zd-mtx-sh.patch -> 1.3
    amanda-no_libnsl.patch -> 1.2

diff --git a/amanda-chg-zd-mtx-sh.patch b/amanda-chg-zd-mtx-sh.patch
--- a/amanda-chg-zd-mtx-sh.patch
+++ b/amanda-chg-zd-mtx-sh.patch
@@ -1,6 +1,6 @@
---- amanda-2.4.3/changer-src/chg-zd-mtx.sh.in.orig	Mon Sep 16 16:36:15 2002
-+++ amanda-2.4.3/changer-src/chg-zd-mtx.sh.in	Thu Jan  9 23:16:47 2003
-@@ -358,7 +358,7 @@
+--- amanda-2.6.0/changer-src/chg-zd-mtx.sh.orig	2008-01-18 01:31:16.000000000 +0100
++++ amanda-2.6.0/changer-src/chg-zd-mtx.sh	2008-05-07 13:00:14.000000000 +0200
+@@ -361,7 +361,7 @@
  
  internal_call=0
  Exit() {
@@ -9,16 +9,31 @@
  		call_type=Return
  	else
  		call_type=Exit
-@@ -370,7 +370,7 @@
+@@ -373,7 +373,7 @@
  	exit_answer="$@"
- 	Log $call_type "($code)" "->" "$exit_slot" "$@"
+ 	Log $call_type "($code) -> $exit_slot $@"
  	echo "$exit_slot" "$@"
 -	if [ $call_type = Return ]; then
 +	if [ "$call_type" = "Return" ]; then
  		return $code
  	fi
- 	amgetconf$SUF dbclose.$argv0:$DBGFILE > /dev/null 2>&1
-@@ -419,13 +419,13 @@
+ 	amgetconf dbclose.$argv0:$DBGFILE > /dev/null 2>&1
+@@ -390,12 +390,12 @@
+ 	"$@" > $stdout 2> $stderr
+ 	exitcode=$?
+ 	Log `_ 'Exit code: %s' "$exitcode"`
+-	if [ -s $stdout ]
++	if [ -s "$stdout" ]
+ 	then
+ 		LogAppend Stdout:
+ 		cat $stdout >> $DBGFILE
+ 	fi
+-	if [ -s $stderr ]
++	if [ -s "$stderr" ]
+ 	then
+ 		LogAppend Stderr:
+ 		cat $stderr >> $DBGFILE
+@@ -422,13 +422,13 @@
  mtx_status_valid=0
  get_mtx_status() {
  	test -n "$DEBUG" && set -x
@@ -34,7 +49,32 @@
  		mtx_status_valid=1
  	fi
  	return $status
-@@ -512,27 +512,27 @@
+@@ -489,7 +489,7 @@
+ 	fi
+ 
+ 	#Use the current slot if it's empty and we don't know which slot is loaded'
+-	if [ $loadedslot -eq -2 ]; then
++	if [ "$loadedslot" -eq -2 ]; then
+ 		set x `sed -n '
+ {
+     /^.*Storage Element '$currentslot':Empty/ {
+@@ -512,13 +512,13 @@
+ ' < $mtx_status 2>& 1`
+ 		shift				# get rid of the "x"
+ 		loadedslotx=$1
+-		if [ ! -z $loadedslotx ]; then
++		if [ ! -z "$loadedslotx" ]; then
+ 			loadedslot=$loadedslotx
+ 		fi
+ 	fi
+ 
+ 	#Use the first empty slot if we don't know which slot is loaded'
+-	if [ $loadedslot -eq -2 ]; then
++	if [ "$loadedslot" -eq -2 ]; then
+ 		set x `sed -n '
+ {
+     /^.*Storage Element \([0-9][0-9]*\):Empty/ {
+@@ -586,27 +586,27 @@
  }
  ' < $mtx_status 2>&1 | grep -v "^${cleanslot}\$" | sort -n`
  	slot_list=`echo $slot_list`		# remove the newlines
@@ -44,7 +84,7 @@
  		for slot in $slot_list; do
 -			if [ $firstslot -lt 0 ]; then
 +			if [ "$firstslot" -lt 0 ]; then
- 				Log "SLOTLIST -> firstslot set to $slot"
+ 				Log `_ 'SLOTLIST -> firstslot set to %s' "$slot"`
  				firstslot=$slot
  			fi
 -			if [ $lastslot -lt 0 ]; then
@@ -54,21 +94,21 @@
  		done
 -		if [ $lastslot -lt 0 -a $last -ge 0 ]; then
 +		if [ "$lastslot" -lt 0 -a "$last" -ge 0 ]; then
- 			Log "SLOTLIST -> lastslot set to $last"
+ 			Log `_ 'SLOTLIST -> lastslot set to %s' "$last"`
  			lastslot=$last
  		fi
 -		if [ $firstslot -lt 0 ]; then
 +		if [ "$firstslot" -lt 0 ]; then
  			Exit 2 \
- 			     "<none>" \
- 			     "cannot determine first slot"
+ 			     `_ '<none>'` \
+ 			     `_ 'cannot determine first slot'`
  			return $?		# in case we are internal
 -		elif [ $lastslot -lt 0 ]; then
 +		elif [ "$lastslot" -lt 0 ]; then
  			Exit 2 \
- 			     "<none>" \
- 			     "cannot determine last slot"
-@@ -541,7 +541,7 @@
+ 			     `_ '<none>'` \
+ 			     `_ 'cannot determine last slot'`
+@@ -615,7 +615,7 @@
  	fi
  	amanda_slot_list=
  	for slot in $slot_list; do
@@ -77,25 +117,63 @@
  			amanda_slot_list="$amanda_slot_list $slot"
  		fi
  	done
-@@ -589,7 +589,7 @@
- 	Exit 2 \
- 	     "<none>" \
- 	     "tapedev may not be empty"
+@@ -652,7 +652,7 @@
+         Exit 2 \
+              ` _ '<none>'` \
+              "tapedev $rawtape is not a tape device."
 -elif [ $tape = "/dev/null" -o `expr "$tape" : 'null:'` -eq 5 ]; then
-+elif [ "$tape" = "/dev/null" -o `expr "$tape" : 'null:'` -eq 5 ]; then
++elif [ "$tape" = "/dev/null" -o "`expr "$tape" : 'null:'`" -eq 5 ]; then
  	Exit 2 \
- 	     "<none>" \
+ 	     `_ '<none>'` \
  	     "tapedev ($tape) may not be the null device"
-@@ -599,7 +599,7 @@
+@@ -663,7 +663,7 @@
  	Exit 2 \
- 	     "<none>" \
+ 	     `_ '<none>'` \
  	     "changerdev may not be empty"
 -elif [ $TAPE = "/dev/null" ]; then
 +elif [ "$TAPE" = "/dev/null" ]; then
  	Exit 2 \
- 	     "<none>" \
+ 	     `_ '<none>'` \
  	     "changerdev ($TAPE) may not be the null device"
-@@ -674,7 +674,7 @@
+@@ -676,19 +676,19 @@
+ #### Set up the various config files.
+ 
+ conf_match=`expr "$changerfile" : .\*\.conf\$`
+-if [ $conf_match -ge 6 ]; then
++if [ "$conf_match" -ge 6 ]; then
+ 	configfile=$changerfile
+ 	changerfile=`echo $changerfile | sed 's/.conf$//g'`
+ else
+ 	configfile=$changerfile.conf
+ fi
+ 
+-if [ ! -e $configfile ]; then
++if [ ! -e "$configfile" ]; then
+ 	Exit 2 \
+ 	     `_ '<none>'` \
+ 	     "configuration file \"$configfile\" doesn't exist"
+ fi
+-if [ ! -f $configfile ]; then
++if [ ! -f "$configfile" ]; then
+ 	Exit 2 \
+ 	     `_ '<none>'` \
+ 	     "configuration file \"$configfile\" is not a file"
+@@ -698,10 +698,10 @@
+ accessfile=$changerfile-access
+ slotfile=$changerfile-slot
+ labelfile=$changerfile-barcodes
+-[ ! -s $cleanfile ] && echo 0 > $cleanfile
+-[ ! -s $accessfile ] && echo 0 > $accessfile
+-[ ! -s $slotfile ] && echo -1 > $slotfile
+-[ ! -f $labelfile ] && > $labelfile
++[ ! -s "$cleanfile" ] && echo 0 > $cleanfile
++[ ! -s "$accessfile" ] && echo 0 > $accessfile
++[ ! -s "$slotfile" ] && echo -1 > $slotfile
++[ ! -f "$labelfile" ] && > $labelfile
+ cleancount=`cat $cleanfile`
+ accesscount=`cat $accessfile`
+ 
+@@ -747,7 +747,7 @@
  
  # Get DBGFILE set if it is not already.
  
@@ -104,9 +182,9 @@
  	if [ -d "$DBGDIR" ]; then
  		DBGFILE=$DBGDIR/changer.debug.drive$driveslot
  	else
-@@ -729,9 +729,9 @@
+@@ -827,9 +827,9 @@
  
- Log "Config info:"
+ Log `_ "Config info:"`
  for var in $varlist; do
 -	if [ $var = "OFFLINE_BEFORE_UNLOAD" ]; then
 +	if [ "$var" = "OFFLINE_BEFORE_UNLOAD" ]; then
@@ -116,43 +194,40 @@
  		continue			# old name
  	fi
  	eval val=\"'$'$var\"
-@@ -752,13 +752,13 @@
+@@ -850,12 +850,12 @@
  
  # Run the rest of the config file sanity checks.
  
 -if [ $firstslot -gt $lastslot ]; then
 +if [ "$firstslot" -gt "$lastslot" ]; then
  	Exit 2 \
- 	     "<none>" \
- 	     "firstslot ($firstslot) greater than" \
- 	     "lastslot ($lastslot) in $configfile"
+ 	     `_ '<none>'` \
+ 	     `_ 'firstslot (%s) greater than lastslot (%s) in %s' "$firstslot" "$lastslot" "$configfile"`
  fi
 -if [ $autoclean -ne 0 -a $cleanslot -lt 0 ]; then
 +if [ "$autoclean" -ne 0 -a "$cleanslot" -lt 0 ]; then
  	Exit 2 \
- 	     "<none>" \
- 	     "autoclean set but cleanslot not valid ($cleanslot)"
-@@ -768,12 +768,12 @@
+ 	     `_ '<none>'` \
+ 	     `_ 'autoclean set but cleanslot not valid (%s)' "$cleanslot"`
+@@ -865,10 +865,10 @@
  
  currentslot=`cat $slotfile`
  if IsNumeric "$currentslot" ; then
 -	if [ $currentslot -lt $firstslot ]; then
 +	if [ "$currentslot" -lt "$firstslot" ]; then
- 		Log "SETUP    -> current slot $currentslot" \
- 				 "less than $firstslot ..." \
- 				 "resetting to $firstslot"
+ 		Log `_ 'SETUP    -> current slot %s less than %s ... resetting to %s' "$currentslot" "$firstslot" "$firstslot"`
  		currentslot=$firstslot
 -	elif [ $currentslot -gt $lastslot ]; then
 +	elif [ "$currentslot" -gt "$lastslot" ]; then
- 		Log "SETUP    -> current slot $currentslot" \
- 				 "greater than $lastslot ..." \
- 				 "resetting to $lastslot"
-@@ -789,19 +789,19 @@
+ 		Log `_ 'SETUP    -> current slot %s greater than %s ... resetting to %s' "$currentslot" "$lastslot" "$lastslot"`
+ 		currentslot=$lastslot
+ 	fi
+@@ -881,19 +881,19 @@
  first_slot_in_list=-1
  next_slot_after_current=-1
  for slot in $slot_list; do
 -	if [ $first_slot_in_list -lt 0 ]; then
-+	if [ "$first_slot"_in_list -lt 0 ]; then
++	if [ "$first_slot_in_list" -lt 0 ]; then
  		first_slot_in_list=$slot	# in case $firstslot is missing
  	fi
 -	if [ $slot -eq $currentslot ]; then
@@ -172,29 +247,28 @@
  		new_currentslot=$first_slot_in_list
  	else
  		new_currentslot=$next_slot_after_current
-@@ -821,10 +821,10 @@
+@@ -912,9 +912,9 @@
  	test -n "$DEBUG" && set -x
- 	Log "EJECT    -> ejecting tape from $tape"
+ 	Log `_ 'EJECT    -> ejecting tape from %s' "$tape"`
  	get_loaded_info 
 -	if [ $loadedslot -gt 0 ]; then
 +	if [ "$loadedslot" -gt 0 ]; then
- 		Log "EJECT    -> moving tape from drive $driveslot" \
- 				 "to storage slot $loadedslot"
+ 		Log `_ 'EJECT    -> moving tape from drive %s to storage slot %s' "$driveslot" "$loadedslot"`
 -		if [ $offline_before_unload -ne 0 ]; then
 +		if [ "$offline_before_unload" -ne 0 ]; then
- 			Run $MT $MTF $tape offline > /dev/null 2>&1
+                         Run try_eject_device $tape
  		fi
  		sleep $unloadpause
-@@ -832,7 +832,7 @@
+@@ -922,7 +922,7 @@
  		status=$?
- 		Log "         -> status $status, result \"$result\""
+ 		Log `_ '         -> status %s, result "%s"' "$status" "$result"`
  		mtx_status_valid=0
 -		if [ $status -ne 0 ]; then
 +		if [ "$status" -ne 0 ]; then
  			answer="$result"
  			code=2
  		else
-@@ -912,7 +912,7 @@
+@@ -1001,7 +1001,7 @@
  	prev_slot=$1
  	shift
  	while [ $# -gt 0 ]; do
@@ -203,7 +277,7 @@
  			break
  		fi
  		prev_slot=$1
-@@ -942,8 +942,8 @@
+@@ -1030,15 +1030,15 @@
  	# If the desired slot is already loaded, we are done.  Only update
  	# current slot if this is not the cleaning slot.
  	get_loaded_info
@@ -214,7 +288,15 @@
  			rm -f $slotfile
  			echo $loadslot > $slotfile
  		fi
-@@ -954,20 +954,20 @@
+ 		Exit 0 "$loadedslot" "$rawtape"
+ 		return $?			# in case we are internal
+ 	fi
+-	if [ $loadedslot -eq -2 ]; then
++	if [ "$loadedslot" -eq -2 ]; then
+ 		Exit 0 "$loadedslot" "$rawtape"
+ 		return $?			# in case we are internal
+         fi
+@@ -1046,20 +1046,20 @@
  	# If we are loading the cleaning tape, bump the cleaning count
  	# and reset the access count.  Otherwise, bump the access count
  	# and see if it is time to do a cleaning.
@@ -238,7 +320,7 @@
  				Exit $status "$loadslot" "$exit_answer"
  				return $?	# in case we are internal
  			fi
-@@ -987,14 +987,14 @@
+@@ -1079,14 +1079,14 @@
  	eject > /dev/null 2>&1
  	status=$?
  	internal_call=`expr $internal_call - 1`
@@ -256,33 +338,40 @@
  			rm -f $slotfile
  			echo $loadslot > $slotfile
  		fi
-@@ -1009,7 +1009,7 @@
+@@ -1100,7 +1100,7 @@
  	status=$?
- 	Log "         -> status $status, result \"$result\""
+ 	Log `_ '         -> status %s, result "%s"' "$status" "$result"`
  	mtx_status_valid=0
 -	if [ $status -ne 0 ]; then
 +	if [ "$status" -ne 0 ]; then
  		Exit 2 "$loadslot" "$result"
  		return $?			# in case we are internal
  	fi
-@@ -1019,7 +1019,7 @@
+@@ -1110,7 +1110,7 @@
  	# for "long enough" (as determined empirically by the user),
  	# then return success.
  	###
 -	if [ $loadslot -eq $cleanslot ]; then
 +	if [ "$loadslot" -eq "$cleanslot" ]; then
  		Run sleep $cleancycle
- 		Exit 0 "$loadslot" "$tape"
+ 		Exit 0 "$loadslot" "$rawtape"
  		return $?			# in case we are internal
-@@ -1039,14 +1039,14 @@
+@@ -1122,7 +1122,7 @@
+ 	waittime=0
+ 	ready=0
+ 	sleep $initial_poll_delay
+-	while [ $waittime -lt $max_drive_wait ]; do
++	while [ "$waittime" -lt "$max_drive_wait" ]; do
+                 amdevcheck_status $tape
+ 		if [ $? -eq 0 ]; then
+ 			ready=1
+@@ -1131,12 +1131,12 @@
  		sleep $poll_drive_ready
  		waittime=`expr $waittime + $poll_drive_ready`
  	done
 -	if [ $ready -eq 0 ]; then
 +	if [ "$ready" -eq 0 ]; then
- 		Exit 2 "$loadslot" "Drive not ready after" \
- 				   "$max_drive_wait seconds," \
- 				   "rewind said \"$result\""
+ 		Exit 2 "$loadslot" `_ 'Drive not ready after %s seconds, rewind said "%s"' "$max_drive_wait" "$result"`
  		return $?			# in case we are internal
  	fi
  
@@ -291,7 +380,7 @@
  		rm -f $slotfile
  		echo $loadslot > $slotfile
  	fi
-@@ -1077,11 +1077,11 @@
+@@ -1167,11 +1167,11 @@
  	# can search based on barcodes.
  	###
  	reader=
@@ -304,55 +393,53 @@
 +	if [ "$currentslot" -lt "$firstslot" -o "$currentslot" -gt "$lastslot" ]; then
  		currentslot=$firstslot		# what "current" will get
  	fi
- 	set x $slot_list
-@@ -1116,8 +1116,8 @@
- 			     "Line $line malformed in $labelfile: $lbl $bc $junk"
+ 	numslots=`expr $lastslot - $firstslot + 1`
+@@ -1202,7 +1202,7 @@
+ 			     `_ 'Line %s malformed in %s: %s %s %s' "$line" "$labelfile" "$lbl" "$bc" "$junk"`
  			return $?		# in case we are internal
  		fi
 -		if [ $lbl = "$lbl_search" -o $bc = "$bc_search" ]; then
--			if [ $labelfile_entry_found -ne 0 ]; then
 +		if [ "$lbl" = "$lbl_search" -o "$bc" = "$bc_search" ]; then
-+			if [ "$labelfile_entry_found" -ne 0 ]; then
- 				Log       "ERROR    -> Duplicate entries: $labelfile line $line"
- 				LogAppend "         -> Remove $labelfile" \
- 						       "and run" \
-@@ -1146,12 +1146,12 @@
+ 			if [ $labelfile_entry_found -ne 0 ]; then
+ 				Log       `_ 'ERROR    -> Duplicate entries: %s line %s' "$labelfile" "$line"`
+ 				LogAppend `_ '         -> Remove %s and run "%s %s update"' "$labelfile" "$sbindir/amtape" "$config"`
+@@ -1230,12 +1230,12 @@
  		return $?			# in case we are internal
  	fi
          tapelabel=$1
 -	if [ $havereader -eq 0 ]; then
 +	if [ "$havereader" -eq 0 ]; then
- 		Exit 2 "<none>" "Not configured with barcode reader"
+ 		Exit 2 `_ '<none>'` `_ 'Not configured with barcode reader'`
  		return $?			# in case we are internal
  	fi
          get_loaded_info
 -	if [ $loadedslot -lt 0 ]; then
 +	if [ "$loadedslot" -lt 0 ]; then
- 		Exit 1 "<none>" "No tape currently loaded"
+ 		Exit 1 `_ '<none>'` `_ 'No tape currently loaded'`
  		return $?			# in case we are internal
  	fi
-@@ -1160,7 +1160,7 @@
- 			       "for slot $loadedslot" \
- 			       "into $labelfile"
+@@ -1245,7 +1245,7 @@
+ 	fi
+ 	Log       `_ 'LABEL    -> Adding label "%s" with barcode "%s" for slot %s into %s' "$tapelabel" "$loadedbarcode" "$loadedslot" "$labelfile"`
  	read_labelfile "$tapelabel" "$loadedbarcode" < $labelfile
 -	if [ $labelfile_entry_found -ne 0 ]; then
 +	if [ "$labelfile_entry_found" -ne 0 ]; then
  		lf_val=
  		if [ "$labelfile_barcode" != "$loadedbarcode" ]; then
  			lf_type=label
-@@ -1212,13 +1212,13 @@
+@@ -1289,13 +1289,13 @@
  		return $?			# in case we are internal
  	fi
          tapelabel=$1
 -	if [ $havereader -eq 0 ]; then
 +	if [ "$havereader" -eq 0 ]; then
- 		Exit 2 "<none>" "Not configured with barcode reader"
+ 		Exit 2 `_ '<none>'` `_ 'Not configured with barcode reader'`
  		return $?			# in case we are internal
  	fi
- 	Log "SEARCH   -> Hunting for label \"$tapelabel\""
+ 	Log `_ 'SEARCH   -> Hunting for label "%s"' "$tapelabel"`
  	read_labelfile "$tapelabel" "" < $labelfile
 -	if [ $labelfile_entry_found -eq 0 ]; then
 +	if [ "$labelfile_entry_found" -eq 0 ]; then
- 		LogAppend "         -> !!! label \"$tapelabel\" not found" \
- 				       "in $labelfile !!!"
- 		LogAppend "         -> Remove $labelfile" \
+ 		LogAppend `_ '         -> !!! label "%s" not found in %s !!!' "$tapelabel" "$labelfile"`
+ 		LogAppend `_ '         -> Remove %s and run "%s %s update"' "$labelfile" "$sbindir/amtape" "$config"`
+ 		Exit 2 \
